import "server-only";

import { ImapFlow } from "imapflow";
import { simpleParser } from "mailparser";
import nodemailer from "nodemailer";
import { classifyMailError } from "./failures";
import type {
  FetchResult,
  FetchedMessage,
  MailAttachment,
  MailCursor,
  MailOutcome,
  MailSource,
  MailboxCredentials,
} from "./source";

/**
 * Gmail over IMAP and SMTP, authenticated with an app password.
 *
 * Chosen over the Gmail API because every API scope that can read mail is a
 * *restricted* scope: an OAuth app left in testing hands out refresh tokens that
 * die after seven days, and publishing one requires verification and a security
 * assessment renewed annually. An app password is generated by the company
 * inside their own Google account, never expires, and can be revoked by them at
 * any moment — which is also how the revocation test in checklist item 5 gets
 * performed for real rather than simulated.
 *
 * A connection is opened per sync and closed again. There is no long-lived IDLE
 * session, because a request-scoped server action is not somewhere to keep a
 * socket alive.
 */

const IMAP_HOST = "imap.gmail.com";
const IMAP_PORT = 993;
const SMTP_HOST = "smtp.gmail.com";
const SMTP_PORT = 465;

/** Bounded like the AI client is: a hung socket must not hang the request. */
const TIMEOUT_MS = 20_000;

/** Stored body ceiling. Triage clips far shorter; this stops a mail bomb. */
const BODY_CHARS = 8_000;
const MAX_PARAGRAPHS = 40;

function client(credentials: MailboxCredentials): ImapFlow {
  return new ImapFlow({
    host: IMAP_HOST,
    port: IMAP_PORT,
    secure: true,
    auth: { user: credentials.address, pass: credentials.appPassword },
    // The library logs every command at info level otherwise, which would put
    // message subjects into the server log.
    logger: false,
    greetingTimeout: TIMEOUT_MS,
    socketTimeout: TIMEOUT_MS,
    connectionTimeout: TIMEOUT_MS,
  });
}

/** Crude but sufficient: only reached for mail with no plain-text part at all. */
function htmlToText(html: string): string {
  return html
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<\/p>/gi, "\n\n")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, "\"")
    .replace(/[ \t]+/g, " ");
}

function toParagraphs(text: string): string[] {
  return text
    .slice(0, BODY_CHARS)
    .split(/\r?\n\s*\r?\n/)
    .map((paragraph) => paragraph.replace(/\s+/g, " ").trim())
    .filter(Boolean)
    .slice(0, MAX_PARAGRAPHS);
}

export function createImapSource(credentials: MailboxCredentials): MailSource {
  /** Every network call goes through here, so none of them can throw upward. */
  async function guarded<T>(
    run: (connection: ImapFlow) => Promise<T>,
  ): Promise<MailOutcome<T>> {
    const connection = client(credentials);

    /**
     * ImapFlow is an EventEmitter, and an emitter with no `error` listener
     * turns any late error into an uncaught exception — which takes the whole
     * server process down, not just this request.
     *
     * That is not hypothetical: a rejected sign-in returns here in about two
     * seconds, then the abandoned socket times out twenty seconds later and
     * emits on its own. Absorbing it is what lets a revoked app password be
     * reported on screen instead of crashing the server, which is precisely
     * what checklist item 5 asks us to demonstrate.
     */
    connection.on("error", () => {
      // Deliberately empty. The outcome of the operation is decided by the
      // try/catch below; anything arriving after that has nowhere to go.
    });

    try {
      await connection.connect();
    } catch (cause) {
      // A failed connect can still leave a socket open, which is what times
      // out later. Close it here rather than leaving it to expire.
      connection.close();
      return {
        ok: false,
        reason: classifyMailError(cause),
        detail: cause instanceof Error ? cause.message : String(cause),
      };
    }

    try {
      return { ok: true, data: await run(connection) };
    } catch (cause) {
      return {
        ok: false,
        reason: classifyMailError(cause),
        detail: cause instanceof Error ? cause.message : String(cause),
      };
    } finally {
      // logout() can itself throw on an already-broken socket; failing to hang
      // up politely must not become the error the user is shown.
      await connection.logout().catch(() => connection.close());
    }
  }

  return {
    async verify() {
      const result = await guarded(async (connection) => {
        const lock = await connection.getMailboxLock("INBOX");
        lock.release();
        return true as const;
      });
      return result.ok ? { ok: true, data: true } : result;
    },

    async fetchSince(cursor: MailCursor, limit: number) {
      return guarded(async (connection): Promise<FetchResult> => {
        const lock = await connection.getMailboxLock("INBOX");

        try {
          const mailbox = connection.mailbox;
          if (!mailbox || typeof mailbox === "boolean") {
            throw new Error("mailbox does not exist");
          }

          const uidValidity = String(mailbox.uidValidity);
          const total = mailbox.exists;

          /**
           * A changed uidValidity means the server has reissued every UID, so
           * the stored high-water mark now points at an unrelated message.
           * Starting over is the only safe reading of that.
           */
          const fresh =
            cursor.uidValidity !== uidValidity || cursor.lastUid === null;

          if (total === 0) {
            return {
              messages: [],
              cursor: { uidValidity, lastUid: cursor.lastUid },
              initialImport: fresh,
            };
          }

          const previousUid = cursor.lastUid ?? 0;

          // First run: the newest `limit` by sequence number. Later runs:
          // everything above the high-water mark, by UID.
          const range = fresh
            ? `${Math.max(1, total - limit + 1)}:${total}`
            : `${previousUid + 1}:*`;

          const messages: FetchedMessage[] = [];
          let highest = fresh ? 0 : previousUid;

          for await (const item of connection.fetch(
            range,
            { uid: true, source: true, flags: true },
            { uid: !fresh },
          )) {
            // `n:*` is defined to return the last message even when nothing is
            // above n, so this guard is required rather than defensive.
            if (!fresh && item.uid <= previousUid) continue;
            if (messages.length >= limit) break;
            // The server can answer a fetch without the body it was asked for.
            // Skipping keeps the UID high-water mark honest: the message is not
            // recorded, so a later run will not believe it was already read.
            if (!item.source) continue;

            const parsed = await simpleParser(item.source);
            const address = parsed.from?.value?.[0];
            const email = address?.address?.trim() ?? "";
            const plain =
              parsed.text ??
              (typeof parsed.html === "string" ? htmlToText(parsed.html) : "");

            messages.push({
              // Message-ID is stable across re-fetches; a UID is not stable
              // across a uidValidity change, so it is only the fallback.
              messageId:
                parsed.messageId?.trim() || `${uidValidity}:${item.uid}`,
              from: address?.name?.trim() || email || "Unknown sender",
              email,
              subject: parsed.subject?.trim() || "(no subject)",
              body: toParagraphs(plain),
              receivedAt: parsed.date ?? new Date(),
              unread: !item.flags?.has("\\Seen"),
              uid: item.uid,
              uidValidity,
            });

            if (item.uid > highest) highest = item.uid;
          }

          return {
            messages,
            cursor: { uidValidity, lastUid: highest || cursor.lastUid },
            initialImport: fresh,
          };
        } finally {
          lock.release();
        }
      });
    },

    async setSeen(uid: number, uidValidity: string, seen: boolean) {
      const result = await guarded(async (connection) => {
        const lock = await connection.getMailboxLock("INBOX");
        try {
          const mailbox = connection.mailbox;
          if (!mailbox || typeof mailbox === "boolean") {
            throw new Error("mailbox does not exist");
          }

          /**
           * The UID was recorded against a particular uidValidity. If the
           * server has reissued its UIDs since, that number now points at some
           * other message, and marking a stranger's mail read is worse than
           * refusing to mark anything.
           */
          if (String(mailbox.uidValidity) !== uidValidity) {
            throw new Error("uid no longer valid for this mailbox");
          }

          const range = { uid: String(uid) };
          const options = { uid: true };
          await (seen
            ? connection.messageFlagsAdd(range, ["\\Seen"], options)
            : connection.messageFlagsRemove(range, ["\\Seen"], options));

          return true as const;
        } finally {
          lock.release();
        }
      });

      return result.ok ? { ok: true as const, data: true as const } : result;
    },

    async send(to: string, subject: string, body: string, attachments: MailAttachment[] = []) {
      try {
        const transport = nodemailer.createTransport({
          host: SMTP_HOST,
          port: SMTP_PORT,
          secure: true,
          auth: { user: credentials.address, pass: credentials.appPassword },
          connectionTimeout: TIMEOUT_MS,
          greetingTimeout: TIMEOUT_MS,
          socketTimeout: TIMEOUT_MS,
        });

        // Plain text only, and never nodemailer's `raw` option: the message is
        // composed from fields AEGIS controls rather than assembled from input.
        await transport.sendMail({
          from: credentials.address,
          to,
          subject,
          text: body,
          // Buffers AEGIS built itself, never a path or URL: nodemailer would
          // read a file or fetch an address named there.
          attachments: attachments.map((file) => ({
            filename: file.filename,
            content: file.content,
            contentType: file.contentType,
          })),
        });

        return { ok: true, data: true as const };
      } catch (cause) {
        return {
          ok: false,
          reason: classifyMailError(cause),
          detail: cause instanceof Error ? cause.message : String(cause),
        };
      }
    },
  };
}
