import "server-only";

import { readCachedOutput } from "@/lib/dal/ai";
import { buildReport } from "@/lib/dal/report";
import { formatMoney, formatMoneyIn } from "@/lib/format";
import { parseReportSummary } from "@/lib/report";
import { AI_MODELS } from "./client";
import { cacheKeyFor, generate } from "./generate";
import type { AiResult, DateRange, Report, ReportSummary } from "@/types";

/**
 * The full report's longer AI summary.
 *
 * Spend behaviour, which is the point of how this is built:
 *
 * - it is never generated by opening the report; only the "Write AI summary"
 *   button asks for it;
 * - the answer is cached against a hash of the figures below, so a report is
 *   paid for once and re-served until the numbers themselves move;
 * - the input is figures and the business's own labels (service, campaign and
 *   item names). No customer names, phone numbers, plates, email subjects or
 *   senders are sent;
 * - the DEMO DATA tiles (balance, expenses, net profit) are left out entirely,
 *   so the model never reasons over a number that is not real.
 */

const PROMPT_VERSION = 1;
const MAX_OUTPUT_TOKENS = 650;

const KIND = "dashboard-report" as const;

/**
 * The length limits are stated in words rather than as `maxItems`, which strict
 * structured output does not accept; `parseReportSummary` enforces them.
 */
const lines = (max: number, description: string) => ({
  type: "array",
  items: { type: "string" },
  description: `${description} At most ${max}.`,
});

const SCHEMA = {
  type: "object",
  properties: {
    headline: {
      type: "string",
      description: "One sentence: the most important thing the figures say about the period.",
    },
    highlights: lines(4, "What went well or stands out, one short sentence each, quoting the figure."),
    risks: lines(3, "What needs attention, one short sentence each, quoting the figure. Empty if nothing does."),
    actions: lines(3, "Concrete next steps a shop owner could take this week. Empty if none follow from the figures."),
  },
  required: ["headline", "highlights", "risks", "actions"],
  additionalProperties: false,
} as const;

const INSTRUCTIONS = [
  "You write the executive summary of an operations report for the owner of a small business.",
  "You are given the report's figures for one period as JSON. Summarise what they show.",
  "Quote the figures you reason from. Never invent a number, a name or a cause that is not in the input.",
  "The ads figures cover the last 30 days, not the report period; say 'in the last 30 days' when you use them and do not compare them with period figures as if they matched.",
  "Revenue is recognised when a booking is made, so call it booked revenue, not cash received.",
  "A section missing from the input is not tracked; do not mention it or guess at it.",
  "Do not commit the business to anything: suggest, never promise.",
  "If a list has nothing real to say, return it empty rather than padding it.",
  "Plain words, short sentences, no headings or markdown.",
].join(" ");

/**
 * The figures the model sees, and the cache key. Anything that changes on its
 * own, such as the time the report was opened or how long ago mail synced, is
 * left out on purpose: it would make every view a cache miss.
 */
export function reportFacts(report: Report) {
  const money = (cents: number) => formatMoney(cents);
  const { ads } = report;

  return {
    period: { range: report.period.range, dates: report.period.label },
    revenue: {
      booked: money(report.revenue.totalCents),
      previousPeriod: money(report.revenue.previousCents),
      change: report.revenue.change,
      byMonth: report.revenue.months.map((month) => ({
        month: month.label,
        booked: money(month.totalCents),
      })),
    },
    bookings: report.bookings && {
      total: report.bookings.total,
      bookedValue: money(report.bookings.bookedValueCents),
      byStatus: Object.fromEntries(report.bookings.byStatus.map((row) => [row.status, row.count])),
      byChannel: Object.fromEntries(report.bookings.byChannel.map((row) => [row.channel, row.count])),
      topServices: report.bookings.topServices.map((row) => ({
        service: row.service,
        bookings: row.count,
        value: money(row.valueCents),
      })),
      fromOnlineBookingPage: report.bookings.online,
    },
    adsLast30Days: ads && {
      spend: formatMoneyIn(ads.spendCents, ads.currency),
      results: ads.resultLabel ? `${ads.results} ${ads.resultLabel}` : "mixed result types",
      costPerResult: ads.resultLabel ? formatMoneyIn(ads.costPerResultCents, ads.currency) : null,
      topCampaigns: ads.campaigns.slice(0, 3).map((row) => ({
        campaign: row.name,
        spend: formatMoneyIn(row.spendCents, ads.currency),
        results: `${row.results} ${row.resultLabel}`,
      })),
    },
    mail: report.mail && {
      received: report.mail.received,
      unread: report.mail.unread,
      needingApproval: report.mail.needsApproval,
      byPriority: Object.fromEntries(report.mail.byPriority.map((row) => [row.priority, row.count])),
      byCategory: Object.fromEntries(report.mail.byCategory.map((row) => [row.category, row.count])),
    },
    inventoryNow: report.inventory && {
      itemsTracked: report.inventory.skus,
      stockValue: money(report.inventory.stockValueCents),
      belowReorder: report.inventory.belowReorderCount,
      lowItems: report.inventory.belowReorder.slice(0, 5).map((item) => ({
        item: item.name,
        onHand: item.onHand,
        reorderAt: item.reorder,
      })),
    },
    fleet: report.fleet && {
      vehiclesOnFile: report.fleet.vehicles,
      overdueForServiceNow: report.fleet.overdue,
      dueWithin30DaysNow: report.fleet.dueSoon,
      servicesRecordedInPeriod: report.fleet.servicesInPeriod,
    },
    customers: report.customers && {
      total: report.customers.total,
      newInPeriod: report.customers.newInPeriod,
    },
  };
}

/**
 * A summary already written for exactly these figures, or null. A cache read
 * and nothing else, so it is safe on the render path: it cannot start a
 * billable request.
 */
export async function cachedReportSummary(report: Report): Promise<ReportSummary | null> {
  return readCachedOutput<ReportSummary>(KIND, cacheKeyFor(reportFacts(report)), PROMPT_VERSION);
}

/**
 * Writes the summary for a range. The figures are rebuilt here, on the server,
 * from the tenant's own collections; nothing the browser sends reaches the
 * prompt except which of the three ranges to use.
 */
export async function generateReportSummary(range: DateRange): Promise<AiResult<ReportSummary>> {
  const report = await buildReport(range);
  if (!report) return { ok: false, reason: "error" };

  const facts = reportFacts(report);
  return generate<ReportSummary>({
    kind: KIND,
    cacheKey: cacheKeyFor(facts),
    promptVersion: PROMPT_VERSION,
    model: AI_MODELS.reasoning,
    instructions: INSTRUCTIONS,
    input: JSON.stringify(facts),
    maxOutputTokens: MAX_OUTPUT_TOKENS,
    schemaName: "dashboard_report_summary",
    schema: SCHEMA as unknown as Record<string, unknown>,
    parse: parseReportSummary,
  });
}
