"use client";

import type { CSSProperties } from "react";
import { Button } from "./button";
import { Icon } from "./icon";

export interface InsightPanelProps {
  title?: string;
  body: string;
  action?: string;
  onAction?: () => void;
  className?: string;
  style?: CSSProperties;
}

export function InsightPanel({
  title = "AI Insight",
  body,
  action,
  onAction,
  className,
  style,
}: InsightPanelProps) {
  return (
    <section
      className={className}
      style={{
        background: "var(--surface-card)",
        border: "1px solid var(--border-default)",
        borderRadius: "var(--radius-lg)",
        padding: "var(--card-padding)",
        display: "flex",
        flexDirection: "column",
        gap: "14px",
        overflow: "hidden",
        ...style,
      }}
    >
      <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
        <Icon name="sparkles" size={16} color="var(--accent-primary)" />
        <h3
          style={{
            fontFamily: "var(--font-display)",
            fontSize: "var(--text-h3-size)",
            fontWeight: 600,
            color: "var(--text-primary)",
          }}
        >
          {title}
        </h3>
      </div>
      <p
        style={{
          margin: 0,
          fontSize: "13px",
          lineHeight: "20px",
          color: "var(--text-secondary)",
          textWrap: "pretty",
        }}
      >
        {body}
      </p>
      <div
        style={{
          flex: 1,
          minHeight: 120,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        {/* The orb is the only non-flat element in the system: glow means "generated by AI". */}
        <div
          style={{
            width: 132,
            height: 132,
            borderRadius: "50%",
            background: "var(--grad-orb)",
            boxShadow: "var(--glow-orb)",
            animation:
              "aegis-orb var(--dur-ambient) var(--ease-in-out) infinite",
          }}
        />
      </div>
      {action && (
        <Button variant="outline" fullWidth onClick={onAction}>
          {action}
        </Button>
      )}
    </section>
  );
}
